ALTER TABLE customers
  ADD COLUMN IF NOT EXISTS pan VARCHAR(10),
  ADD COLUMN IF NOT EXISTS sac_code VARCHAR(20),
  ADD COLUMN IF NOT EXISTS vendor_code VARCHAR(50);

ALTER TABLE owners_vendors
  ADD COLUMN IF NOT EXISTS aadhar_number VARCHAR(12);

ALTER TABLE drivers
  ADD COLUMN IF NOT EXISTS aadhar_number VARCHAR(12);
